# Generated by Django 5.1 on 2024-09-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overallresult",
            name="kb_squat_points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="overallresult",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.player"
            ),
        ),
        migrations.AlterField(
            model_name="overallresult",
            name="see_saw_press_points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="overallresult",
            name="snatch_points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="overallresult",
            name="tgu_points",
            field=models.FloatField(default=0),
        ),
    ]
