# Generated by Django 5.1 on 2024-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="seesawpressweight", name="player",),
        migrations.RemoveField(model_name="snatchresults", name="player",),
        migrations.RemoveField(model_name="tguresults", name="player",),
        migrations.AddField(
            model_name="player",
            name="kb_sqad_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="see_saw_press_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_sum_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="Results2xKBSQAD",),
        migrations.DeleteModel(name="SeeSawPressWeight",),
        migrations.DeleteModel(name="SnatchResults",),
        migrations.DeleteModel(name="TGUResults",),
    ]
