# Generated by Django 5.1 on 2024-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_remove_tguresult_result_tguresult_result_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="tgu_weight", new_name="tgu_weight_1",
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_weight_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_weight_3",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
