# Generated by Django 5.1 on 2024-08-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_remove_seesawpressweight_player_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="snatch_sum_weight",
            new_name="number_of_snatches",
        ),
    ]
