# Generated by Django 5.1 on 2024-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_rename_snatch_sum_weight_player_number_of_snatches"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="snatch_kettlebell_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_repetitions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="number_of_snatches",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
