# Generated by Django 5.1 on 2024-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_rename_tgu_weight_player_tgu_weight_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="disciplines",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
