# Generated by Django 5.1 on 2024-09-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_category_disciplines_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="overallresult",
            name="pistol_squat_points",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="pistol_squat_weight_1",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="pistol_squat_weight_2",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="pistol_squat_weight_3",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="snatch_kettlebell_weight",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="snatch_repetitions",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="tgu_weight_1",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="tgu_weight_2",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="tgu_weight_3",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="PistolSquatResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_1", models.FloatField(default=0)),
                ("result_2", models.FloatField(default=0)),
                ("result_3", models.FloatField(default=0)),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
    ]
