# Generated by Django 5.1 on 2024-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_player_snatch_kettlebell_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="number_of_snatches",),
    ]
