# Generated by Django 5.1 on 2024-08-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0005_remove_player_number_of_snatches"),
    ]

    operations = [
        migrations.RenameModel(old_name="WeightCategory", new_name="Category",),
    ]
