# Generated by Django 5.1 on 2024-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0006_rename_weightcategory_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="level",),
        migrations.RemoveField(model_name="player", name="category",),
        migrations.AddField(
            model_name="player",
            name="categories",
            field=models.ManyToManyField(to="tournament.category"),
        ),
        migrations.DeleteModel(name="Level",),
    ]
