# Generated by Django 5.1 on 2024-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0007_remove_player_level_remove_player_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="kb_sqad_place",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="see_saw_press_place",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_place",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_place",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
