# Generated by Django 5.1 on 2024-08-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0008_player_kb_sqad_place_player_see_saw_press_place_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="weight",),
    ]
