# Generated by Django 5.1 on 2024-08-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0009_remove_category_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="kb_sqad_place", new_name="final_score",
        ),
        migrations.RemoveField(model_name="player", name="see_saw_press_place",),
        migrations.RemoveField(model_name="player", name="snatch_place",),
        migrations.RemoveField(model_name="player", name="tgu_place",),
    ]
