# Generated by Django 5.1 on 2024-08-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0010_rename_kb_sqad_place_player_final_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="final_score",),
        migrations.RemoveField(model_name="player", name="kb_sqad_weight",),
        migrations.RemoveField(model_name="player", name="see_saw_press_weight",),
        migrations.RemoveField(model_name="player", name="snatch_kettlebell_weight",),
        migrations.RemoveField(model_name="player", name="snatch_repetitions",),
        migrations.RemoveField(model_name="player", name="tgu_weight",),
        migrations.AddField(
            model_name="player",
            name="kb_sqad_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="see_saw_press_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="KBSqadResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("body_weight_percentage", models.FloatField()),
                ("place", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.category",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeeSawPressResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("body_weight_percentage", models.FloatField()),
                ("place", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.category",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kettlebell_weight", models.FloatField()),
                ("repetitions", models.IntegerField()),
                ("result", models.FloatField()),
                ("place", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.category",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TGUResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("body_weight_percentage", models.FloatField()),
                ("place", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.category",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
    ]
