# Generated by Django 5.1 on 2024-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0011_remove_player_final_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="seesawpressresult", name="category",),
        migrations.RemoveField(model_name="seesawpressresult", name="player",),
        migrations.RemoveField(model_name="snatchresult", name="category",),
        migrations.RemoveField(model_name="snatchresult", name="player",),
        migrations.RemoveField(model_name="tguresult", name="category",),
        migrations.RemoveField(model_name="tguresult", name="player",),
        migrations.RemoveField(model_name="player", name="kb_sqad_points",),
        migrations.RemoveField(model_name="player", name="see_saw_press_points",),
        migrations.RemoveField(model_name="player", name="snatch_points",),
        migrations.RemoveField(model_name="player", name="tgu_points",),
        migrations.AddField(
            model_name="player",
            name="final_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="kb_sqad_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="see_saw_press_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_kettlebell_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_repetitions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="KBSqadResult",),
        migrations.DeleteModel(name="SeeSawPressResult",),
        migrations.DeleteModel(name="SnatchResult",),
        migrations.DeleteModel(name="TGUResult",),
    ]
