# Generated by Django 5.1 on 2024-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0012_remove_seesawpressresult_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="kb_sqad_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="see_saw_press_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="snatch_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="tgu_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
