# Generated by Django 5.1 on 2024-08-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0013_player_kb_sqad_score_player_see_saw_press_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="kb_sqad_weight", new_name="kb_squat_weight",
        ),
        migrations.RemoveField(model_name="player", name="final_score",),
        migrations.RemoveField(model_name="player", name="kb_sqad_score",),
        migrations.RemoveField(model_name="player", name="see_saw_press_score",),
        migrations.RemoveField(model_name="player", name="snatch_score",),
        migrations.RemoveField(model_name="player", name="tgu_score",),
    ]
